common: &common
  access_key_id: AKIAIWWQF5REKTC4ZYGQ
 secret_access_key: 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

development:
   <<: *common
   bucket: dnyanarths2




test:
   <<: *common
   bucket: dnyanarths2




production:
   <<: *common
   bucket: dnyanarths2


